# Generated by Django 5.1.7 on 2025-04-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
        migrations.AddField(
            model_name='note',
            name='vector_uuid',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
